# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: GAP
email: your-email@domain.com
author: Open Data Kosovo / Instituti GAP
description:  Kjo faqe përmban vizualizime të të dhënave dhe kalkulator për llogaritjen e doganës së veturave.
baseurl: /veturat
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: http://opendatakosovo.github.io/veturat/
  - title: linkedin
    url: 
