# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Tabled
email: your-email@domain.com
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/tabledapp
  - title: facebook
    url: hhttps://www.facebook.com/tabledapp
  - title: 
    url: 
