# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: GAP
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."
baseurl: /veturat
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: http://opendatakosovo.github.io/veturat/
  - title: linkedin
    url: 
